// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_knLRKMKTyZsaL0SomjlCOHLIty4711M',
    appId: '1:923457405525:android:fe1152e13de093a06c4adc',
    messagingSenderId: '923457405525',
    projectId: 'sufh1-d02e8',
    databaseURL: 'https://sufh1-d02e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sufh1-d02e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQm3GibZygwuWtDmHOMoWHUlDwCZDTCVQ',
    appId: '1:923457405525:ios:6ccb2a79e9162e3c6c4adc',
    messagingSenderId: '923457405525',
    projectId: 'sufh1-d02e8',
    databaseURL: 'https://sufh1-d02e8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sufh1-d02e8.firebasestorage.app',
    iosBundleId: 'com.example.sufh1App',
  );
}
